---
- hosts: localhost
  tasks:
    - name: install packages
      become: true
      become_user: root
      apt:
        name:
          - alacritty
          - exa
          - bat
          - neovim
          - ripgrep
        state: present

    - name: Set environment variable for Neovim
      ansible.builtin.shell: export PATH="$PATH:/opt/nvim-linux64/bin"
      environment:
        PATH: "{{ ansible_env.PATH }}:/opt/nvim-linux64/bin"

    - name: Download and extract Neovim
      ansible.builtin.shell: |
        curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
        sudo rm -rf /opt/nvim
        sudo tar -C /opt -xzf nvim-linux64.tar.gz

    - name: Remove existing neovim config directory
      ansible.builtin.file:
        path: ~/.config/nvim
        state: absent

    - name: Clone neovim configuration
      ansible.builtin.shell:
        cmd: git clone https://github.com/Phenox11/nvim.git ~/.config/nvim

