---
- hosts: localhost
  tasks:
    - name: install packages
      become: true
      become_user: root
      apt:
        state: present
        name:
          - alacritty
          - zellij
          - eza
          - bat
          - neovim

    - name: neovim
      ansible.builtin.shell: |
        curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
        sudo rm -rf /opt/nvim
        sudo tar -C /opt -xzf nvim-linux64.tar.gz
        export PATH="$PATH:/opt/nvim-linux64/bin"
