---
- hosts: localhost
  become: true

  tasks:

    - name: Install packages
      apt:
        state: present
        name:
          - alacritty
          - exa
          - bat
          - neovim
          - ripgrep

    - name: Install Neovim
      block:

        - name: Download Neovim
          unarchive:
            src: https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
            dest: /opt
            remote_src: yes
            creates: /opt/nvim-linux64

        - name: Add Neovim to PATH
          become: true
          lineinfile:
            path: /etc/environment
            line: 'PATH="/opt/nvim-linux64/bin:$PATH"'

      become: true

    - name: Remove existing neovim config directory
      file:
        path: ~/.config/nvim
        state: absent

    - name: Clone neovim configuration
      git:
        repo: https://github.com/Phenox11/nvim.git
        dest: ~/.config/nvim
